// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/9/28 20:57:02
const configMerger = require("D:/github-project/Visualization/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/github-project/Visualization/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/github-project/Visualization/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/github-project/Visualization/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/github-project/Visualization/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/github-project/Visualization/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/github-project/Visualization/plugins/**/*.{js,ts,mjs}","D:/github-project/Visualization/composables/**/*.{js,ts,mjs}","D:/github-project/Visualization/utils/**/*.{js,ts,mjs}","D:/github-project/Visualization/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/github-project/Visualization/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/github-project/Visualization/app.config.{js,ts,mjs}"] }));

module.exports = config
